# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ "1.19", "1.20" ]
        pg-version: [ 13, 14, 15 ]
      fail-fast: false
    env:
      PGLOGREPL_TEST_CONN_STRING: "postgres://pglogrepl:secret@127.0.0.1/pglogrepl?replication=database"
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: Stand up Postgres ${{ matrix.pg-version }}
      run: docker-compose up -d postgres
      env:
        POSTGRES_VERSION: ${{ matrix.pg-version }}

    - name: Test
      run: go test -v ./...
